wandb_version: 1

K:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
activation_function:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: complete
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.1
embed_dim:
  desc: null
  value: 128
env:
  desc: null
  value: kitchen-complete
learning_rate:
  desc: null
  value: 0.0001
log_to_wandb:
  desc: null
  value: true
max_iters:
  desc: null
  value: 10
mode:
  desc: null
  value: normal
model_savepath:
  desc: null
  value: /home/jlw2247/DT/outputs/
model_type:
  desc: null
  value: dt
n_head:
  desc: null
  value: 1
n_layer:
  desc: null
  value: 3
num_eval_episodes:
  desc: null
  value: 100
num_steps_per_iter:
  desc: null
  value: 10000
pct_traj:
  desc: null
  value: 1.0
warmup_steps:
  desc: null
  value: 10000
weight_decay:
  desc: null
  value: 0.0001
